args<-commandArgs(trailingOnly=TRUE)
args2<-paste(args,"result.csv",sep="")
data<-read.csv(args,header=TRUE)
library("dplyr")
output<-data %>% group_by(gene_id) %>% summarise_each(funs(sum))
write.csv(output,args2,row.names=FALSE)
